/**
 * 
 */
package com.sivalabs.sample;


/**
 * @author skatam
 *
 */

public class AppInitializer
{
	private HibernateUserDAO userDAO;
	public void setHibernateUserDAO(HibernateUserDAO userDAO)
	{
		this.userDAO = userDAO;
	}
	
	public void init()
	{
		this.userDAO.deleteAllUsers();
		User admin = new User(1, "admin", "admin", "Administrator", "admin@sivalabs.com");
		User test = new User(2, "test", "test", "Test", "test@sivalabs.com");
		this.userDAO.create(admin);
		this.userDAO.create(test);
	}
	/*
	private JdbcTemplate jdbcTemplate;
	
	public void setJdbcTemplate(JdbcTemplate jdbcTemplate)
	{
		this.jdbcTemplate = jdbcTemplate;
	}
		
	public void init()
	{
		String sql = "DROP TABLE USERS IF EXISTS";
		this.jdbcTemplate.execute(sql);

		sql = "create table users(id integer GENERATED BY DEFAULT AS IDENTITY, " +
					 " user_id varchar(30), password varchar(30), username varchar(30), " +
					 " email_id varchar(30))";
		this.jdbcTemplate.execute(sql);
		
		sql = "insert into users(user_id,password,username,email_id) values(?,?,?,?)";
		Object[] args = {"admin","admin","Administrator","admin@sivalabs.com"};
		this.jdbcTemplate.update(sql, args);
		
	}
	*/
}
