spring.application.name=03-chat-memory

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-5
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
