spring.application.name=01-chat-openai

#spring.ai.openai.base-url=https://api.openai.com
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-5
# The temperature value should be between 0 and 1.
# higher number -> more creative and random
# lower number -> more deterministic
# gpt-5 supports temperature=1 only
spring.ai.openai.chat.temperature=1
