spring.application.name=02-structured-output

#spring.ai.openai.base-url=https://api.openai.com
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-5

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
